name: Lousch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36710908845998347
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8997618891298771
  lightness: 0.5890957373194396
  saturation: 0.37454282911494374
  rhythmicContrast: 0.15859612985514104
purpose: []
